#!/bin/bash
#SBATCH -J mem_10
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --ntasks-per-node=1
#SBATCH --time=6-0
#
date
source /home/prog/amber22/amber.sh

packmol-memgen --pdb full_bak_10.pdb  --lipids POPC --n_ter out --dist 12 --dist_wat 12 --salt --salt_c Na+ --minimize --random 


